version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: code-server_server_1
      APP_PORT: 8080

  server:
    image: codercom/code-server:4.18.0@sha256:29267847d68332a28d249bd5235715402b144a3903b921da0a1962173aef10b1
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
    environment:
      PASSWORD: $APP_PASSWORD
