version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bazarr_server_1
      APP_PORT: 6767
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/bazarr:1.3.1@sha256:dedc43e90ca36e034f7e4fa3b119e6d4f70f5f82823e532c7ac3678fc1f950d8
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
